// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Radix2wDPM_point_add_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        ap_return_0,
        ap_return_1
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [165:0] p_read;
input  [165:0] p_read1;
input  [331:0] p_read2;
output  [165:0] ap_return_0;
output  [165:0] ap_return_1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[165:0] ap_return_0;
reg[165:0] ap_return_1;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [162:0] trunc_ln1068_fu_188_p1;
reg   [162:0] trunc_ln1068_reg_651;
wire   [165:0] rhs_V_fu_192_p1;
wire   [165:0] rhs_V_8_fu_202_p4;
wire   [0:0] and_ln99_fu_228_p2;
reg   [0:0] and_ln99_reg_666;
wire   [0:0] icmp_ln100_fu_240_p2;
reg   [0:0] icmp_ln100_reg_670;
wire   [0:0] icmp_ln1064_fu_246_p2;
reg   [0:0] icmp_ln1064_reg_674;
wire   [165:0] ret_24_fu_252_p2;
reg   [165:0] ret_24_reg_706;
wire   [162:0] ret_25_fu_270_p2;
reg   [162:0] ret_25_reg_711;
wire   [0:0] xor_ln1544_21_fu_276_p2;
reg   [0:0] xor_ln1544_21_reg_716;
wire   [164:0] trunc_ln1068_4_fu_314_p1;
reg   [164:0] trunc_ln1068_4_reg_730;
wire    ap_CS_fsm_state2;
wire   [165:0] tmp_V_21_fu_325_p3;
reg   [165:0] tmp_V_21_reg_738;
wire   [0:0] icmp_ln1068_4_fu_319_p2;
reg   [165:0] v_V_4_load_reg_743;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_23_fu_369_p3;
reg   [0:0] tmp_23_reg_748;
wire    ap_CS_fsm_state5;
wire  signed [16:0] j_4_fu_383_p3;
reg  signed [16:0] j_4_reg_756;
reg   [0:0] tmp_24_reg_762;
reg   [165:0] g_V_load_reg_768;
wire    ap_CS_fsm_state6;
wire   [165:0] select_ln1691_fu_457_p3;
reg   [165:0] select_ln1691_reg_773;
wire   [165:0] r_4_fu_464_p3;
reg   [165:0] r_4_reg_778;
wire   [164:0] empty_fu_514_p1;
reg   [164:0] empty_reg_786;
wire    ap_CS_fsm_state9;
wire   [162:0] empty_51_fu_519_p1;
reg   [162:0] empty_51_reg_791;
wire   [0:0] empty_52_fu_524_p1;
reg   [0:0] empty_52_reg_797;
wire   [165:0] tmp_V_22_fu_528_p3;
reg   [165:0] tmp_V_22_reg_802;
wire   [165:0] d_V_fu_550_p2;
reg   [165:0] d_V_reg_807;
wire    ap_CS_fsm_state11;
wire   [164:0] trunc_ln1544_8_fu_561_p1;
reg   [164:0] trunc_ln1544_8_reg_813;
wire   [165:0] tmp_V_24_fu_566_p3;
reg   [165:0] tmp_V_24_reg_818;
wire    ap_CS_fsm_state15;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_start;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_done;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_idle;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_ready;
wire   [165:0] grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_c_V_9_out;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_c_V_9_out_ap_vld;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_start;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_done;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_idle;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_ready;
wire   [15:0] grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_i_out;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_i_out_ap_vld;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_start;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_done;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_idle;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_ready;
wire   [15:0] grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_i_27_out;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_i_27_out_ap_vld;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_start;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_done;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_idle;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_ready;
wire   [165:0] grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_lhs_V_25_out;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_lhs_V_25_out_ap_vld;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_start;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_done;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_idle;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_ready;
wire   [165:0] grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_lhs_V_30_out;
wire    grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_lhs_V_30_out_ap_vld;
wire    grp_point_double_fu_182_ap_start;
wire    grp_point_double_fu_182_ap_done;
wire    grp_point_double_fu_182_ap_idle;
wire    grp_point_double_fu_182_ap_ready;
wire   [165:0] grp_point_double_fu_182_ap_return_0;
wire   [165:0] grp_point_double_fu_182_ap_return_1;
reg   [165:0] ap_phi_mux_x1_3_phi_fu_116_p10;
reg   [165:0] x1_3_reg_112;
wire    ap_CS_fsm_state13;
wire   [0:0] icmp_ln1064_2_fu_302_p2;
wire   [165:0] ret_fu_581_p2;
reg   [165:0] ap_phi_mux_y1_3_phi_fu_133_p10;
reg   [165:0] y1_3_reg_129;
reg    grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_start_reg;
wire    ap_CS_fsm_state8;
reg    grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_start_reg;
reg    grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_point_double_fu_182_ap_start_reg;
wire    ap_CS_fsm_state14;
reg   [165:0] u_V_16_fu_78;
wire   [165:0] u_V_fu_491_p2;
wire    ap_CS_fsm_state7;
reg   [165:0] v_V_4_fu_82;
wire   [165:0] v_V_fu_408_p3;
reg   [165:0] g_V_fu_86;
wire   [165:0] g_V_4_fu_402_p3;
reg   [165:0] tmp_V_fu_90;
wire   [165:0] ret_23_fu_496_p2;
wire   [0:0] icmp_ln1068_fu_196_p2;
wire   [0:0] icmp_ln1068_3_fu_222_p2;
wire   [165:0] or_ln100_fu_234_p2;
wire   [162:0] trunc_ln1068_3_fu_212_p4;
wire   [0:0] tmp_fu_262_p3;
wire   [0:0] trunc_ln1544_fu_258_p1;
wire   [15:0] add_ln28_fu_343_p2;
wire   [15:0] add_ln28_4_fu_353_p2;
wire   [16:0] zext_ln28_fu_349_p1;
wire   [16:0] zext_ln65_fu_359_p1;
wire   [16:0] j_fu_363_p2;
wire   [16:0] sub_ln69_fu_377_p2;
wire  signed [31:0] sext_ln1691_fu_413_p1;
wire   [165:0] zext_ln1691_fu_416_p1;
wire   [16:0] sub_ln1691_fu_432_p2;
wire  signed [31:0] sext_ln1691_4_fu_437_p1;
wire   [165:0] zext_ln1691_4_fu_441_p1;
wire   [165:0] r_fu_445_p2;
wire   [165:0] shl_ln1691_fu_420_p2;
wire   [165:0] ashr_ln1691_fu_451_p2;
wire   [165:0] shl_ln1691_4_fu_426_p2;
wire   [165:0] u_V_20_fu_486_p3;
wire   [165:0] lhs_V_16_fu_481_p3;
wire   [165:0] xor_ln904_4_fu_545_p2;
wire   [165:0] xor_ln904_fu_540_p2;
wire   [165:0] ret_26_fu_556_p2;
wire   [165:0] xor_ln1544_fu_577_p2;
reg   [165:0] ap_return_0_preg;
reg   [165:0] ap_return_1_preg;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_block_state4_on_subcall_done;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
#0 grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_start_reg = 1'b0;
#0 grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_start_reg = 1'b0;
#0 grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_start_reg = 1'b0;
#0 grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_start_reg = 1'b0;
#0 grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_start_reg = 1'b0;
#0 grp_point_double_fu_182_ap_start_reg = 1'b0;
#0 ap_return_0_preg = 166'd0;
#0 ap_return_1_preg = 166'd0;
end

Radix2wDPM_point_add_1_Pipeline_VITIS_LOOP_45_1 grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_start),
    .ap_done(grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_done),
    .ap_idle(grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_idle),
    .ap_ready(grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_ready),
    .tmp_V_33(tmp_V_21_reg_738),
    .c_V(trunc_ln1068_4_reg_730),
    .ret_33(ret_25_reg_711),
    .c_V_9_out(grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_c_V_9_out),
    .c_V_9_out_ap_vld(grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_c_V_9_out_ap_vld)
);

Radix2wDPM_point_add_1_Pipeline_VITIS_LOOP_25_1 grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_start),
    .ap_done(grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_done),
    .ap_idle(grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_idle),
    .ap_ready(grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_ready),
    .u_V_19(u_V_16_fu_78),
    .i_out(grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_i_out),
    .i_out_ap_vld(grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_i_out_ap_vld)
);

Radix2wDPM_point_add_1_Pipeline_VITIS_LOOP_25_19 grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_start),
    .ap_done(grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_done),
    .ap_idle(grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_idle),
    .ap_ready(grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_ready),
    .v_V_8(v_V_4_fu_82),
    .i_27_out(grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_i_27_out),
    .i_27_out_ap_vld(grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_i_27_out_ap_vld)
);

Radix2wDPM_point_add_1_Pipeline_VITIS_LOOP_45_110 grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_start),
    .ap_done(grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_done),
    .ap_idle(grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_idle),
    .ap_ready(grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_ready),
    .tmp_V_35(tmp_V_22_reg_802),
    .c_V_9_reload(empty_reg_786),
    .c_V_10_cast4(empty_51_reg_791),
    .lhs_V_25_out(grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_lhs_V_25_out),
    .lhs_V_25_out_ap_vld(grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_lhs_V_25_out_ap_vld)
);

Radix2wDPM_point_add_1_Pipeline_VITIS_LOOP_45_111 grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_start),
    .ap_done(grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_done),
    .ap_idle(grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_idle),
    .ap_ready(grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_ready),
    .tmp_V_36(tmp_V_24_reg_818),
    .ret_34(trunc_ln1544_8_reg_813),
    .c_V_10_cast4(empty_51_reg_791),
    .lhs_V_30_out(grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_lhs_V_30_out),
    .lhs_V_30_out_ap_vld(grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_lhs_V_30_out_ap_vld)
);

Radix2wDPM_point_double grp_point_double_fu_182(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_double_fu_182_ap_start),
    .ap_done(grp_point_double_fu_182_ap_done),
    .ap_idle(grp_point_double_fu_182_ap_idle),
    .ap_ready(grp_point_double_fu_182_ap_ready),
    .x_V_read(p_read),
    .y_V_read(trunc_ln1068_reg_651),
    .ap_return_0(grp_point_double_fu_182_ap_return_0),
    .ap_return_1(grp_point_double_fu_182_ap_return_1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 166'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            ap_return_0_preg <= ap_phi_mux_x1_3_phi_fu_116_p10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 166'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            ap_return_1_preg <= ap_phi_mux_y1_3_phi_fu_133_p10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_ready == 1'b1)) begin
            grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_ready == 1'b1)) begin
            grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_ready == 1'b1)) begin
            grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_ready == 1'b1)) begin
            grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1068_4_fu_319_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_ready == 1'b1)) begin
            grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_double_fu_182_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_point_double_fu_182_ap_start_reg <= 1'b1;
        end else if ((grp_point_double_fu_182_ap_ready == 1'b1)) begin
            grp_point_double_fu_182_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1064_fu_246_p2 == 1'd0) & (1'd1 == and_ln99_fu_228_p2) & (icmp_ln100_fu_240_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        g_V_fu_86 <= 166'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        g_V_fu_86 <= g_V_4_fu_402_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1064_fu_246_p2 == 1'd0) & (1'd1 == and_ln99_fu_228_p2) & (icmp_ln100_fu_240_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_V_fu_90 <= 166'd1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_V_fu_90 <= ret_23_fu_496_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1064_fu_246_p2 == 1'd0) & (1'd1 == and_ln99_fu_228_p2) & (icmp_ln100_fu_240_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        u_V_16_fu_78 <= ret_24_fu_252_p2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        u_V_16_fu_78 <= u_V_fu_491_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1064_fu_246_p2 == 1'd0) & (1'd1 == and_ln99_fu_228_p2) & (icmp_ln100_fu_240_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        v_V_4_fu_82 <= 166'd11692013098647223345629478661730264157247460344009;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        v_V_4_fu_82 <= v_V_fu_408_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1064_fu_246_p2 == 1'd1) & (1'd1 == and_ln99_fu_228_p2) & (icmp_ln100_fu_240_p2 == 1'd0) & (icmp_ln1064_2_fu_302_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        x1_3_reg_112 <= 166'd0;
    end else if (((1'd1 == and_ln99_fu_228_p2) & (icmp_ln100_fu_240_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        x1_3_reg_112 <= rhs_V_fu_192_p1;
    end else if (((1'd0 == and_ln99_fu_228_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        x1_3_reg_112 <= p_read;
    end else if (((grp_point_double_fu_182_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        x1_3_reg_112 <= grp_point_double_fu_182_ap_return_0;
    end else if (((icmp_ln1064_reg_674 == 1'd0) & (1'd1 == and_ln99_reg_666) & (icmp_ln100_reg_670 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        x1_3_reg_112 <= d_V_reg_807;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1064_fu_246_p2 == 1'd1) & (1'd1 == and_ln99_fu_228_p2) & (icmp_ln100_fu_240_p2 == 1'd0) & (icmp_ln1064_2_fu_302_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        y1_3_reg_129 <= 166'd0;
    end else if (((1'd1 == and_ln99_fu_228_p2) & (icmp_ln100_fu_240_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        y1_3_reg_129 <= {{p_read2[331:166]}};
    end else if (((1'd0 == and_ln99_fu_228_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        y1_3_reg_129 <= p_read1;
    end else if (((grp_point_double_fu_182_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        y1_3_reg_129 <= grp_point_double_fu_182_ap_return_1;
    end else if (((icmp_ln1064_reg_674 == 1'd0) & (1'd1 == and_ln99_reg_666) & (icmp_ln100_reg_670 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        y1_3_reg_129 <= ret_fu_581_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        and_ln99_reg_666 <= and_ln99_fu_228_p2;
        trunc_ln1068_reg_651 <= trunc_ln1068_fu_188_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        d_V_reg_807 <= d_V_fu_550_p2;
        tmp_V_24_reg_818 <= tmp_V_24_fu_566_p3;
        trunc_ln1544_8_reg_813 <= trunc_ln1544_8_fu_561_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        empty_51_reg_791 <= empty_51_fu_519_p1;
        empty_52_reg_797 <= empty_52_fu_524_p1;
        empty_reg_786 <= empty_fu_514_p1;
        tmp_V_22_reg_802 <= tmp_V_22_fu_528_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        g_V_load_reg_768 <= g_V_fu_86;
        r_4_reg_778 <= r_4_fu_464_p3;
        select_ln1691_reg_773 <= select_ln1691_fu_457_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln99_fu_228_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln100_reg_670 <= icmp_ln100_fu_240_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln99_fu_228_p2) & (icmp_ln100_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln1064_reg_674 <= icmp_ln1064_fu_246_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        j_4_reg_756 <= j_4_fu_383_p3;
        tmp_23_reg_748 <= j_fu_363_p2[32'd16];
        tmp_24_reg_762 <= j_4_fu_383_p3[32'd16];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1064_fu_246_p2 == 1'd0) & (1'd1 == and_ln99_fu_228_p2) & (icmp_ln100_fu_240_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        ret_24_reg_706 <= ret_24_fu_252_p2;
        ret_25_reg_711 <= ret_25_fu_270_p2;
        xor_ln1544_21_reg_716 <= xor_ln1544_21_fu_276_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1068_4_fu_319_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_V_21_reg_738 <= tmp_V_21_fu_325_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln1068_4_reg_730 <= trunc_ln1068_4_fu_314_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v_V_4_load_reg_743 <= v_V_4_fu_82;
    end
end

always @ (*) begin
    if ((grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_point_double_fu_182_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1064_reg_674 == 1'd0) & (1'd1 == and_ln99_reg_666) & (icmp_ln100_reg_670 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_phi_mux_x1_3_phi_fu_116_p10 = d_V_reg_807;
    end else begin
        ap_phi_mux_x1_3_phi_fu_116_p10 = x1_3_reg_112;
    end
end

always @ (*) begin
    if (((icmp_ln1064_reg_674 == 1'd0) & (1'd1 == and_ln99_reg_666) & (icmp_ln100_reg_670 == 1'd0) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_phi_mux_y1_3_phi_fu_133_p10 = ret_fu_581_p2;
    end else begin
        ap_phi_mux_y1_3_phi_fu_133_p10 = y1_3_reg_129;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_return_0 = ap_phi_mux_x1_3_phi_fu_116_p10;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_return_1 = ap_phi_mux_y1_3_phi_fu_133_p10;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln1064_fu_246_p2 == 1'd1) & (1'd1 == and_ln99_fu_228_p2) & (icmp_ln100_fu_240_p2 == 1'd0) & (icmp_ln1064_2_fu_302_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if (((icmp_ln1064_fu_246_p2 == 1'd0) & (1'd1 == and_ln99_fu_228_p2) & (icmp_ln100_fu_240_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((1'd0 == and_ln99_fu_228_p2) | ((icmp_ln100_fu_240_p2 == 1'd1) | ((icmp_ln1064_fu_246_p2 == 1'd1) & (icmp_ln1064_2_fu_302_p2 == 1'd0)))))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln1068_4_fu_319_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_point_double_fu_182_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln28_4_fu_353_p2 = (grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_i_27_out + 16'd1);

assign add_ln28_fu_343_p2 = (grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_i_out + 16'd1);

assign and_ln99_fu_228_p2 = (icmp_ln1068_fu_196_p2 & icmp_ln1068_3_fu_222_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_done == 1'b0) | (grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_done == 1'b0));
end

assign ashr_ln1691_fu_451_p2 = $signed(g_V_4_fu_402_p3) >>> zext_ln1691_4_fu_441_p1;

assign d_V_fu_550_p2 = (xor_ln904_fu_540_p2 ^ xor_ln904_4_fu_545_p2);

assign empty_51_fu_519_p1 = grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_c_V_9_out[162:0];

assign empty_52_fu_524_p1 = grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_c_V_9_out[0:0];

assign empty_fu_514_p1 = grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_c_V_9_out[164:0];

assign g_V_4_fu_402_p3 = ((tmp_23_reg_748[0:0] == 1'b1) ? tmp_V_fu_90 : g_V_fu_86);

assign grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_start = grp_point_add_1_Pipeline_VITIS_LOOP_25_19_fu_160_ap_start_reg;

assign grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_start = grp_point_add_1_Pipeline_VITIS_LOOP_25_1_fu_154_ap_start_reg;

assign grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_start = grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_ap_start_reg;

assign grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_start = grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_ap_start_reg;

assign grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_start = grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_ap_start_reg;

assign grp_point_double_fu_182_ap_start = grp_point_double_fu_182_ap_start_reg;

assign icmp_ln100_fu_240_p2 = ((or_ln100_fu_234_p2 == 166'd0) ? 1'b1 : 1'b0);

assign icmp_ln1064_2_fu_302_p2 = ((rhs_V_8_fu_202_p4 == p_read1) ? 1'b1 : 1'b0);

assign icmp_ln1064_fu_246_p2 = ((rhs_V_fu_192_p1 == p_read) ? 1'b1 : 1'b0);

assign icmp_ln1068_3_fu_222_p2 = ((rhs_V_8_fu_202_p4 != 166'd0) ? 1'b1 : 1'b0);

assign icmp_ln1068_4_fu_319_p2 = ((u_V_16_fu_78 == 166'd1) ? 1'b1 : 1'b0);

assign icmp_ln1068_fu_196_p2 = ((rhs_V_fu_192_p1 != 166'd0) ? 1'b1 : 1'b0);

assign j_4_fu_383_p3 = ((tmp_23_fu_369_p3[0:0] == 1'b1) ? sub_ln69_fu_377_p2 : j_fu_363_p2);

assign j_fu_363_p2 = (zext_ln28_fu_349_p1 - zext_ln65_fu_359_p1);

assign lhs_V_16_fu_481_p3 = ((tmp_23_reg_748[0:0] == 1'b1) ? g_V_load_reg_768 : tmp_V_fu_90);

assign or_ln100_fu_234_p2 = (p_read1 | p_read);

assign r_4_fu_464_p3 = ((tmp_24_reg_762[0:0] == 1'b1) ? ashr_ln1691_fu_451_p2 : shl_ln1691_4_fu_426_p2);

assign r_fu_445_p2 = $signed(v_V_fu_408_p3) >>> zext_ln1691_4_fu_441_p1;

assign ret_23_fu_496_p2 = (r_4_reg_778 ^ lhs_V_16_fu_481_p3);

assign ret_24_fu_252_p2 = (rhs_V_fu_192_p1 ^ p_read);

assign ret_25_fu_270_p2 = (trunc_ln1068_fu_188_p1 ^ trunc_ln1068_3_fu_212_p4);

assign ret_26_fu_556_p2 = (p_read ^ d_V_fu_550_p2);

assign ret_fu_581_p2 = (xor_ln1544_fu_577_p2 ^ grp_point_add_1_Pipeline_VITIS_LOOP_45_111_fu_174_lhs_V_30_out);

assign rhs_V_8_fu_202_p4 = {{p_read2[331:166]}};

assign rhs_V_fu_192_p1 = p_read2[165:0];

assign select_ln1691_fu_457_p3 = ((tmp_24_reg_762[0:0] == 1'b1) ? r_fu_445_p2 : shl_ln1691_fu_420_p2);

assign sext_ln1691_4_fu_437_p1 = $signed(sub_ln1691_fu_432_p2);

assign sext_ln1691_fu_413_p1 = j_4_reg_756;

assign shl_ln1691_4_fu_426_p2 = g_V_4_fu_402_p3 << zext_ln1691_fu_416_p1;

assign shl_ln1691_fu_420_p2 = v_V_fu_408_p3 << zext_ln1691_fu_416_p1;

assign sub_ln1691_fu_432_p2 = ($signed(17'd0) - $signed(j_4_reg_756));

assign sub_ln69_fu_377_p2 = (17'd0 - j_fu_363_p2);

assign tmp_23_fu_369_p3 = j_fu_363_p2[32'd16];

assign tmp_V_21_fu_325_p3 = ((xor_ln1544_21_reg_716[0:0] == 1'b1) ? tmp_V_fu_90 : 166'd0);

assign tmp_V_22_fu_528_p3 = ((empty_52_fu_524_p1[0:0] == 1'b1) ? grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_c_V_9_out : 166'd0);

assign tmp_V_24_fu_566_p3 = ((empty_52_reg_797[0:0] == 1'b1) ? ret_26_fu_556_p2 : 166'd0);

assign tmp_fu_262_p3 = p_read2[32'd166];

assign trunc_ln1068_3_fu_212_p4 = {{p_read2[328:166]}};

assign trunc_ln1068_4_fu_314_p1 = tmp_V_fu_90[164:0];

assign trunc_ln1068_fu_188_p1 = p_read1[162:0];

assign trunc_ln1544_8_fu_561_p1 = ret_26_fu_556_p2[164:0];

assign trunc_ln1544_fu_258_p1 = p_read1[0:0];

assign u_V_20_fu_486_p3 = ((tmp_23_reg_748[0:0] == 1'b1) ? v_V_4_load_reg_743 : u_V_16_fu_78);

assign u_V_fu_491_p2 = (u_V_20_fu_486_p3 ^ select_ln1691_reg_773);

assign v_V_fu_408_p3 = ((tmp_23_reg_748[0:0] == 1'b1) ? u_V_16_fu_78 : v_V_4_fu_82);

assign xor_ln1544_21_fu_276_p2 = (trunc_ln1544_fu_258_p1 ^ tmp_fu_262_p3);

assign xor_ln1544_fu_577_p2 = (p_read1 ^ d_V_reg_807);

assign xor_ln904_4_fu_545_p2 = (grp_point_add_1_Pipeline_VITIS_LOOP_45_1_fu_146_c_V_9_out ^ 166'd1);

assign xor_ln904_fu_540_p2 = (ret_24_reg_706 ^ grp_point_add_1_Pipeline_VITIS_LOOP_45_110_fu_166_lhs_V_25_out);

assign zext_ln1691_4_fu_441_p1 = $unsigned(sext_ln1691_4_fu_437_p1);

assign zext_ln1691_fu_416_p1 = $unsigned(sext_ln1691_fu_413_p1);

assign zext_ln28_fu_349_p1 = add_ln28_fu_343_p2;

assign zext_ln65_fu_359_p1 = add_ln28_4_fu_353_p2;

endmodule //Radix2wDPM_point_add_1
