// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Radix2wDPM_point_double_1_Pipeline_VITIS_LOOP_45_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        lambda_V,
        lambda_V_1,
        p_Val2_s,
        lambda_V_12_out,
        lambda_V_12_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [165:0] lambda_V;
input  [164:0] lambda_V_1;
input  [162:0] p_Val2_s;
output  [165:0] lambda_V_12_out;
output   lambda_V_12_out_ap_vld;

reg ap_idle;
reg lambda_V_12_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln45_fu_109_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [7:0] i_1_fu_54;
wire   [7:0] i_9_fu_190_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [164:0] tmp_V_2_in_fu_58;
wire   [164:0] trunc_ln38_fu_151_p1;
reg   [165:0] lhs_V_fu_62;
wire   [165:0] lambda_V_2_fu_184_p2;
wire    ap_block_pp0_stage0_01001;
wire   [165:0] tmp_V_fu_121_p3;
wire   [0:0] p_Result_s_fu_129_p3;
wire   [165:0] xor_ln1544_fu_137_p2;
wire   [165:0] tmp_V_7_fu_143_p3;
wire   [162:0] zext_ln820_fu_155_p1;
wire   [162:0] shl_ln820_fu_159_p2;
wire   [162:0] and_ln820_fu_165_p2;
wire   [0:0] p_Result_13_fu_170_p2;
wire   [165:0] select_ln50_fu_176_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

Radix2wDPM_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_1_fu_54 <= 8'd1;
        end else if (((icmp_ln45_fu_109_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_1_fu_54 <= i_9_fu_190_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            lhs_V_fu_62 <= lambda_V;
        end else if (((icmp_ln45_fu_109_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            lhs_V_fu_62 <= lambda_V_2_fu_184_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            tmp_V_2_in_fu_58 <= lambda_V_1;
        end else if (((icmp_ln45_fu_109_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            tmp_V_2_in_fu_58 <= trunc_ln38_fu_151_p1;
        end
    end
end

always @ (*) begin
    if (((icmp_ln45_fu_109_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln45_fu_109_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lambda_V_12_out_ap_vld = 1'b1;
    end else begin
        lambda_V_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln820_fu_165_p2 = (shl_ln820_fu_159_p2 & p_Val2_s);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign i_9_fu_190_p2 = (i_1_fu_54 + 8'd1);

assign icmp_ln45_fu_109_p2 = ((i_1_fu_54 == 8'd163) ? 1'b1 : 1'b0);

assign lambda_V_12_out = lhs_V_fu_62;

assign lambda_V_2_fu_184_p2 = (select_ln50_fu_176_p3 ^ lhs_V_fu_62);

assign p_Result_13_fu_170_p2 = ((and_ln820_fu_165_p2 != 163'd0) ? 1'b1 : 1'b0);

assign p_Result_s_fu_129_p3 = tmp_V_2_in_fu_58[32'd162];

assign select_ln50_fu_176_p3 = ((p_Result_13_fu_170_p2[0:0] == 1'b1) ? tmp_V_7_fu_143_p3 : 166'd0);

assign shl_ln820_fu_159_p2 = 163'd1 << zext_ln820_fu_155_p1;

assign tmp_V_7_fu_143_p3 = ((p_Result_s_fu_129_p3[0:0] == 1'b1) ? xor_ln1544_fu_137_p2 : tmp_V_fu_121_p3);

assign tmp_V_fu_121_p3 = {{tmp_V_2_in_fu_58}, {1'd0}};

assign trunc_ln38_fu_151_p1 = tmp_V_7_fu_143_p3[164:0];

assign xor_ln1544_fu_137_p2 = (tmp_V_fu_121_p3 ^ 166'd11692013098647223345629478661730264157247460344009);

assign zext_ln820_fu_155_p1 = i_1_fu_54;

endmodule //Radix2wDPM_point_double_1_Pipeline_VITIS_LOOP_45_1
