# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/HardwareAcceleratedECC-PointMultiplication/ScalarMultiplication/vivado-IP/project_1/project_1.srcs/sources_1/bd/design_2/ip/design_2_Radix2wECC_0_1/design_2_Radix2wECC_0_1.xci
# IP: The module: 'design_2_Radix2wECC_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/HardwareAcceleratedECC-PointMultiplication/ScalarMultiplication/vivado-IP/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_Radix2wECC_0_1/constraints/Radix2wECC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_Radix2wECC_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/HardwareAcceleratedECC-PointMultiplication/ScalarMultiplication/vivado-IP/project_1/project_1.srcs/sources_1/bd/design_2/ip/design_2_Radix2wECC_0_1/design_2_Radix2wECC_0_1.xci
# IP: The module: 'design_2_Radix2wECC_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/HardwareAcceleratedECC-PointMultiplication/ScalarMultiplication/vivado-IP/project_1/project_1.gen/sources_1/bd/design_2/ip/design_2_Radix2wECC_0_1/constraints/Radix2wECC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_Radix2wECC_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
