
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xradix2wecc.h"

/*
* The configuration table for devices
*/

XRadix2wecc_Config XRadix2wecc_ConfigTable[XPAR_XRADIX2WECC_NUM_INSTANCES] =
{
	{
		XPAR_RADIX2WECC_0_DEVICE_ID,
		XPAR_RADIX2WECC_0_S_AXI_CONTROL_BASEADDR
	}
};


