set SynModuleInfo {
  {SRCNAME Radix2wECC_Pipeline_1 MODELNAME Radix2wECC_Pipeline_1 RTLNAME Radix2wECC_Radix2wECC_Pipeline_1
    SUBMODULES {
      {MODELNAME Radix2wECC_flow_control_loop_pipe_sequential_init RTLNAME Radix2wECC_flow_control_loop_pipe_sequential_init BINDTYPE interface TYPE internal_upc_flow_control INSTNAME Radix2wECC_flow_control_loop_pipe_sequential_init_U}
    }
  }
  {SRCNAME Radix2wECC_Pipeline_2 MODELNAME Radix2wECC_Pipeline_2 RTLNAME Radix2wECC_Radix2wECC_Pipeline_2}
  {SRCNAME Radix2wECC_Pipeline_3 MODELNAME Radix2wECC_Pipeline_3 RTLNAME Radix2wECC_Radix2wECC_Pipeline_3}
  {SRCNAME Radix2wECC_Pipeline_VITIS_LOOP_33_1 MODELNAME Radix2wECC_Pipeline_VITIS_LOOP_33_1 RTLNAME Radix2wECC_Radix2wECC_Pipeline_VITIS_LOOP_33_1}
  {SRCNAME Radix2wECC_Pipeline_VITIS_LOOP_36_2 MODELNAME Radix2wECC_Pipeline_VITIS_LOOP_36_2 RTLNAME Radix2wECC_Radix2wECC_Pipeline_VITIS_LOOP_36_2}
  {SRCNAME Radix2wECC_Pipeline_VITIS_LOOP_39_3 MODELNAME Radix2wECC_Pipeline_VITIS_LOOP_39_3 RTLNAME Radix2wECC_Radix2wECC_Pipeline_VITIS_LOOP_39_3}
  {SRCNAME bf_inv_Pipeline_VITIS_LOOP_25_1 MODELNAME bf_inv_Pipeline_VITIS_LOOP_25_1 RTLNAME Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_25_1}
  {SRCNAME bf_inv_Pipeline_VITIS_LOOP_25_18 MODELNAME bf_inv_Pipeline_VITIS_LOOP_25_18 RTLNAME Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_25_18}
  {SRCNAME bf_inv_Pipeline_VITIS_LOOP_33_1 MODELNAME bf_inv_Pipeline_VITIS_LOOP_33_1 RTLNAME Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_33_1}
  {SRCNAME bf_inv_Pipeline_VITIS_LOOP_33_19 MODELNAME bf_inv_Pipeline_VITIS_LOOP_33_19 RTLNAME Radix2wECC_bf_inv_Pipeline_VITIS_LOOP_33_19}
  {SRCNAME bf_inv MODELNAME bf_inv RTLNAME Radix2wECC_bf_inv}
  {SRCNAME bf_mult.1_Pipeline_VITIS_LOOP_33_1 MODELNAME bf_mult_1_Pipeline_VITIS_LOOP_33_1 RTLNAME Radix2wECC_bf_mult_1_Pipeline_VITIS_LOOP_33_1}
  {SRCNAME bf_mult.1_Pipeline_VITIS_LOOP_33_16 MODELNAME bf_mult_1_Pipeline_VITIS_LOOP_33_16 RTLNAME Radix2wECC_bf_mult_1_Pipeline_VITIS_LOOP_33_16}
  {SRCNAME bf_mult.1 MODELNAME bf_mult_1 RTLNAME Radix2wECC_bf_mult_1}
  {SRCNAME Radix2wECC_Pipeline_VITIS_LOOP_33_110 MODELNAME Radix2wECC_Pipeline_VITIS_LOOP_33_110 RTLNAME Radix2wECC_Radix2wECC_Pipeline_VITIS_LOOP_33_110}
  {SRCNAME bf_mult.2_Pipeline_VITIS_LOOP_33_1 MODELNAME bf_mult_2_Pipeline_VITIS_LOOP_33_1 RTLNAME Radix2wECC_bf_mult_2_Pipeline_VITIS_LOOP_33_1}
  {SRCNAME bf_mult.2_Pipeline_VITIS_LOOP_33_15 MODELNAME bf_mult_2_Pipeline_VITIS_LOOP_33_15 RTLNAME Radix2wECC_bf_mult_2_Pipeline_VITIS_LOOP_33_15}
  {SRCNAME bf_mult.2 MODELNAME bf_mult_2 RTLNAME Radix2wECC_bf_mult_2}
  {SRCNAME Radix2wECC_Pipeline_VITIS_LOOP_33_111 MODELNAME Radix2wECC_Pipeline_VITIS_LOOP_33_111 RTLNAME Radix2wECC_Radix2wECC_Pipeline_VITIS_LOOP_33_111}
  {SRCNAME Radix2wECC_Pipeline_VITIS_LOOP_33_112 MODELNAME Radix2wECC_Pipeline_VITIS_LOOP_33_112 RTLNAME Radix2wECC_Radix2wECC_Pipeline_VITIS_LOOP_33_112}
  {SRCNAME point_add_Pipeline_VITIS_LOOP_33_13 MODELNAME point_add_Pipeline_VITIS_LOOP_33_13 RTLNAME Radix2wECC_point_add_Pipeline_VITIS_LOOP_33_13}
  {SRCNAME point_add_Pipeline_VITIS_LOOP_33_14 MODELNAME point_add_Pipeline_VITIS_LOOP_33_14 RTLNAME Radix2wECC_point_add_Pipeline_VITIS_LOOP_33_14}
  {SRCNAME bf_add.1 MODELNAME bf_add_1 RTLNAME Radix2wECC_bf_add_1}
  {SRCNAME bf_mult_Pipeline_VITIS_LOOP_33_1 MODELNAME bf_mult_Pipeline_VITIS_LOOP_33_1 RTLNAME Radix2wECC_bf_mult_Pipeline_VITIS_LOOP_33_1}
  {SRCNAME bf_mult_Pipeline_VITIS_LOOP_33_17 MODELNAME bf_mult_Pipeline_VITIS_LOOP_33_17 RTLNAME Radix2wECC_bf_mult_Pipeline_VITIS_LOOP_33_17}
  {SRCNAME bf_mult MODELNAME bf_mult RTLNAME Radix2wECC_bf_mult}
  {SRCNAME point_add_Pipeline_VITIS_LOOP_33_1 MODELNAME point_add_Pipeline_VITIS_LOOP_33_1 RTLNAME Radix2wECC_point_add_Pipeline_VITIS_LOOP_33_1}
  {SRCNAME point_add_Pipeline_VITIS_LOOP_33_11 MODELNAME point_add_Pipeline_VITIS_LOOP_33_11 RTLNAME Radix2wECC_point_add_Pipeline_VITIS_LOOP_33_11}
  {SRCNAME point_add_Pipeline_VITIS_LOOP_33_12 MODELNAME point_add_Pipeline_VITIS_LOOP_33_12 RTLNAME Radix2wECC_point_add_Pipeline_VITIS_LOOP_33_12}
  {SRCNAME point_add MODELNAME point_add RTLNAME Radix2wECC_point_add}
  {SRCNAME Radix2wECC_Pipeline_VITIS_LOOP_56_6 MODELNAME Radix2wECC_Pipeline_VITIS_LOOP_56_6 RTLNAME Radix2wECC_Radix2wECC_Pipeline_VITIS_LOOP_56_6}
  {SRCNAME Radix2wECC_Pipeline_VITIS_LOOP_92_1 MODELNAME Radix2wECC_Pipeline_VITIS_LOOP_92_1 RTLNAME Radix2wECC_Radix2wECC_Pipeline_VITIS_LOOP_92_1}
  {SRCNAME Radix2wECC_Pipeline_VITIS_LOOP_33_113 MODELNAME Radix2wECC_Pipeline_VITIS_LOOP_33_113 RTLNAME Radix2wECC_Radix2wECC_Pipeline_VITIS_LOOP_33_113}
  {SRCNAME Radix2wECC_Pipeline_VITIS_LOOP_33_114 MODELNAME Radix2wECC_Pipeline_VITIS_LOOP_33_114 RTLNAME Radix2wECC_Radix2wECC_Pipeline_VITIS_LOOP_33_114}
  {SRCNAME Radix2wECC_Pipeline_VITIS_LOOP_33_115 MODELNAME Radix2wECC_Pipeline_VITIS_LOOP_33_115 RTLNAME Radix2wECC_Radix2wECC_Pipeline_VITIS_LOOP_33_115}
  {SRCNAME Radix2wECC_Pipeline_VITIS_LOOP_33_116 MODELNAME Radix2wECC_Pipeline_VITIS_LOOP_33_116 RTLNAME Radix2wECC_Radix2wECC_Pipeline_VITIS_LOOP_33_116}
  {SRCNAME Radix2wECC_Pipeline_VITIS_LOOP_77_7 MODELNAME Radix2wECC_Pipeline_VITIS_LOOP_77_7 RTLNAME Radix2wECC_Radix2wECC_Pipeline_VITIS_LOOP_77_7}
  {SRCNAME Radix2wECC_Pipeline_17 MODELNAME Radix2wECC_Pipeline_17 RTLNAME Radix2wECC_Radix2wECC_Pipeline_17}
  {SRCNAME Radix2wECC_Pipeline_18 MODELNAME Radix2wECC_Pipeline_18 RTLNAME Radix2wECC_Radix2wECC_Pipeline_18}
  {SRCNAME Radix2wECC MODELNAME Radix2wECC RTLNAME Radix2wECC IS_TOP 1
    SUBMODULES {
      {MODELNAME Radix2wECC_values_x_V_RAM_AUTO_1R1W RTLNAME Radix2wECC_values_x_V_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME Radix2wECC_buff1_RAM_AUTO_1R1W RTLNAME Radix2wECC_buff1_RAM_AUTO_1R1W BINDTYPE storage TYPE ram IMPL auto LATENCY 2 ALLOW_PRAGMA 1}
      {MODELNAME Radix2wECC_control_s_axi RTLNAME Radix2wECC_control_s_axi BINDTYPE interface TYPE interface_s_axilite}
      {MODELNAME Radix2wECC_gmem_m_axi RTLNAME Radix2wECC_gmem_m_axi BINDTYPE interface TYPE interface_m_axi}
    }
  }
}
