-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Radix2wDPM_point_double_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    P_read : IN STD_LOGIC_VECTOR (328 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (331 downto 0) );
end;


architecture behav of Radix2wDPM_point_double_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv166_lc_3 : STD_LOGIC_VECTOR (165 downto 0) := "0010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011001001";
    constant ap_const_lv166_lc_2 : STD_LOGIC_VECTOR (165 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv166_lc_1 : STD_LOGIC_VECTOR (165 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv32_A6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100110";
    constant ap_const_lv32_148 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_14B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001011";
    constant ap_const_lv332_lc_2 : STD_LOGIC_VECTOR (331 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal u_V_5_fu_158_p1 : STD_LOGIC_VECTOR (165 downto 0);
    signal u_V_5_reg_640 : STD_LOGIC_VECTOR (165 downto 0);
    signal zext_ln1064_fu_162_p1 : STD_LOGIC_VECTOR (331 downto 0);
    signal trunc_ln58_fu_166_p1 : STD_LOGIC_VECTOR (164 downto 0);
    signal trunc_ln58_reg_652 : STD_LOGIC_VECTOR (164 downto 0);
    signal trunc_ln58_1_fu_170_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln58_1_reg_657 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1064_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1064_reg_663 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1068_fu_206_p1 : STD_LOGIC_VECTOR (164 downto 0);
    signal trunc_ln1068_reg_701 : STD_LOGIC_VECTOR (164 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_Val2_s_reg_709 : STD_LOGIC_VECTOR (162 downto 0);
    signal icmp_ln1068_fu_211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lambda_V_fu_234_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal lambda_V_reg_714 : STD_LOGIC_VECTOR (165 downto 0);
    signal trunc_ln1544_1_fu_243_p1 : STD_LOGIC_VECTOR (162 downto 0);
    signal trunc_ln1544_1_reg_719 : STD_LOGIC_VECTOR (162 downto 0);
    signal p_ph1_fu_252_p3 : STD_LOGIC_VECTOR (331 downto 0);
    signal p_ph1_reg_724 : STD_LOGIC_VECTOR (331 downto 0);
    signal v_V_1_load_reg_729 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_fu_296_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_734 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal j_1_fu_310_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal j_1_reg_742 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_19_reg_748 : STD_LOGIC_VECTOR (0 downto 0);
    signal g_V_load_reg_754 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal select_ln1691_fu_384_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal select_ln1691_reg_759 : STD_LOGIC_VECTOR (165 downto 0);
    signal r_1_fu_391_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal r_1_reg_764 : STD_LOGIC_VECTOR (165 downto 0);
    signal ret_7_fu_449_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal ret_7_reg_769 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal trunc_ln1544_3_fu_454_p1 : STD_LOGIC_VECTOR (164 downto 0);
    signal trunc_ln1544_3_reg_774 : STD_LOGIC_VECTOR (164 downto 0);
    signal xor_ln1544_2_fu_459_p2 : STD_LOGIC_VECTOR (162 downto 0);
    signal xor_ln1544_2_reg_779 : STD_LOGIC_VECTOR (162 downto 0);
    signal xor_ln1544_3_fu_465_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1544_3_reg_784 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln820_1_fu_499_p3 : STD_LOGIC_VECTOR (331 downto 0);
    signal select_ln820_1_reg_789 : STD_LOGIC_VECTOR (331 downto 0);
    signal select_ln820_2_fu_508_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal select_ln820_2_reg_794 : STD_LOGIC_VECTOR (165 downto 0);
    signal trunc_ln84_fu_525_p1 : STD_LOGIC_VECTOR (164 downto 0);
    signal trunc_ln84_reg_799 : STD_LOGIC_VECTOR (164 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ret_8_fu_539_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal ret_8_reg_804 : STD_LOGIC_VECTOR (165 downto 0);
    signal lambda_V_5_fu_552_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal lambda_V_5_reg_810 : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_start : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_done : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_idle : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_ready : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_lambda_V_12_out : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_lambda_V_12_out_ap_vld : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_start : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_done : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_idle : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_ready : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_p_out : STD_LOGIC_VECTOR (331 downto 0);
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_p_out_ap_vld : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_start : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_done : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_idle : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_ready : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_i_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_i_out_ap_vld : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_start : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_done : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_idle : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_ready : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_i_4_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_i_4_out_ap_vld : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_start : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_done : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_idle : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_ready : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_p_out : STD_LOGIC_VECTOR (331 downto 0);
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_p_out_ap_vld : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_p_0_03_i5179_out : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_p_0_03_i5179_out_ap_vld : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_start : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_done : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_idle : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_ready : STD_LOGIC;
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_lambda_V_14_out : STD_LOGIC_VECTOR (165 downto 0);
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_lambda_V_14_out_ap_vld : STD_LOGIC;
    signal xor_i_i77_partset_fu_583_p3 : STD_LOGIC_VECTOR (331 downto 0);
    signal ap_phi_mux_storemerge2_phi_fu_107_p4 : STD_LOGIC_VECTOR (331 downto 0);
    signal storemerge2_reg_104 : STD_LOGIC_VECTOR (331 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_start_reg : STD_LOGIC := '0';
    signal grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_start_reg : STD_LOGIC := '0';
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal u_V_2_fu_82 : STD_LOGIC_VECTOR (165 downto 0);
    signal u_V_fu_418_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal v_V_1_fu_86 : STD_LOGIC_VECTOR (165 downto 0);
    signal v_V_fu_335_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal g_V_fu_90 : STD_LOGIC_VECTOR (165 downto 0);
    signal g_V_1_fu_329_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal tmp_V_fu_94 : STD_LOGIC_VECTOR (165 downto 0);
    signal ret_6_fu_423_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal p_Result_s_fu_227_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln820_fu_246_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal add_ln28_fu_270_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln28_1_fu_280_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln28_fu_276_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln65_fu_286_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal j_fu_290_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln69_fu_304_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1691_fu_340_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1691_fu_343_p1 : STD_LOGIC_VECTOR (165 downto 0);
    signal sub_ln1691_fu_359_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln1691_1_fu_364_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1691_1_fu_368_p1 : STD_LOGIC_VECTOR (165 downto 0);
    signal r_fu_372_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal shl_ln1691_fu_347_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal ashr_ln1691_fu_378_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal shl_ln1691_1_fu_353_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal u_V_6_fu_413_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal lambda_V_9_fu_408_p3 : STD_LOGIC_VECTOR (165 downto 0);
    signal trunc_ln1544_2_fu_445_p1 : STD_LOGIC_VECTOR (162 downto 0);
    signal trunc_ln1544_fu_441_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_473_p4 : STD_LOGIC_VECTOR (165 downto 0);
    signal or_ln40_1_fu_491_p3 : STD_LOGIC_VECTOR (331 downto 0);
    signal and_ln_fu_483_p3 : STD_LOGIC_VECTOR (331 downto 0);
    signal lambda_V_10_fu_520_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal trunc_ln1544_4_fu_535_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1544_fu_530_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_14_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal lhs_V_fu_567_p4 : STD_LOGIC_VECTOR (165 downto 0);
    signal ret_fu_577_p2 : STD_LOGIC_VECTOR (165 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (331 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_block_state4_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_block_state8_on_subcall_done : BOOLEAN;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component Radix2wDPM_point_double_1_Pipeline_VITIS_LOOP_45_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        lambda_V : IN STD_LOGIC_VECTOR (165 downto 0);
        lambda_V_1 : IN STD_LOGIC_VECTOR (164 downto 0);
        p_Val2_s : IN STD_LOGIC_VECTOR (162 downto 0);
        lambda_V_12_out : OUT STD_LOGIC_VECTOR (165 downto 0);
        lambda_V_12_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wDPM_point_double_1_Pipeline_VITIS_LOOP_45_12 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_ph1 : IN STD_LOGIC_VECTOR (331 downto 0);
        trunc_ln6 : IN STD_LOGIC_VECTOR (164 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (331 downto 0);
        p_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wDPM_point_double_1_Pipeline_VITIS_LOOP_25_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        u_V_5 : IN STD_LOGIC_VECTOR (165 downto 0);
        i_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        i_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wDPM_point_double_1_Pipeline_VITIS_LOOP_25_11 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        v_V_2 : IN STD_LOGIC_VECTOR (165 downto 0);
        i_4_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        i_4_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wDPM_point_double_1_Pipeline_VITIS_LOOP_45_13 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        select_ln820_1 : IN STD_LOGIC_VECTOR (331 downto 0);
        select_ln820_2 : IN STD_LOGIC_VECTOR (165 downto 0);
        ret_10 : IN STD_LOGIC_VECTOR (164 downto 0);
        xor_ln1544_3 : IN STD_LOGIC_VECTOR (162 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (331 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_0_03_i5179_out : OUT STD_LOGIC_VECTOR (165 downto 0);
        p_0_03_i5179_out_ap_vld : OUT STD_LOGIC );
    end component;


    component Radix2wDPM_point_double_1_Pipeline_VITIS_LOOP_45_14 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        lambda_V_8 : IN STD_LOGIC_VECTOR (165 downto 0);
        lambda_V_13 : IN STD_LOGIC_VECTOR (164 downto 0);
        ret_11 : IN STD_LOGIC_VECTOR (165 downto 0);
        lambda_V_14_out : OUT STD_LOGIC_VECTOR (165 downto 0);
        lambda_V_14_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113 : component Radix2wDPM_point_double_1_Pipeline_VITIS_LOOP_45_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_start,
        ap_done => grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_done,
        ap_idle => grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_idle,
        ap_ready => grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_ready,
        lambda_V => lambda_V_reg_714,
        lambda_V_1 => trunc_ln1068_reg_701,
        p_Val2_s => p_Val2_s_reg_709,
        lambda_V_12_out => grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_lambda_V_12_out,
        lambda_V_12_out_ap_vld => grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_lambda_V_12_out_ap_vld);

    grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121 : component Radix2wDPM_point_double_1_Pipeline_VITIS_LOOP_45_12
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_start,
        ap_done => grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_done,
        ap_idle => grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_idle,
        ap_ready => grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_ready,
        p_ph1 => p_ph1_reg_724,
        trunc_ln6 => trunc_ln58_reg_652,
        p_out => grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_p_out,
        p_out_ap_vld => grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_p_out_ap_vld);

    grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128 : component Radix2wDPM_point_double_1_Pipeline_VITIS_LOOP_25_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_start,
        ap_done => grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_done,
        ap_idle => grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_idle,
        ap_ready => grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_ready,
        u_V_5 => u_V_2_fu_82,
        i_out => grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_i_out,
        i_out_ap_vld => grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_i_out_ap_vld);

    grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134 : component Radix2wDPM_point_double_1_Pipeline_VITIS_LOOP_25_11
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_start,
        ap_done => grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_done,
        ap_idle => grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_idle,
        ap_ready => grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_ready,
        v_V_2 => v_V_1_fu_86,
        i_4_out => grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_i_4_out,
        i_4_out_ap_vld => grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_i_4_out_ap_vld);

    grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140 : component Radix2wDPM_point_double_1_Pipeline_VITIS_LOOP_45_13
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_start,
        ap_done => grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_done,
        ap_idle => grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_idle,
        ap_ready => grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_ready,
        select_ln820_1 => select_ln820_1_reg_789,
        select_ln820_2 => select_ln820_2_reg_794,
        ret_10 => trunc_ln1544_3_reg_774,
        xor_ln1544_3 => xor_ln1544_2_reg_779,
        p_out => grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_p_out,
        p_out_ap_vld => grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_p_out_ap_vld,
        p_0_03_i5179_out => grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_p_0_03_i5179_out,
        p_0_03_i5179_out_ap_vld => grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_p_0_03_i5179_out_ap_vld);

    grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150 : component Radix2wDPM_point_double_1_Pipeline_VITIS_LOOP_45_14
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_start,
        ap_done => grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_done,
        ap_idle => grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_idle,
        ap_ready => grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_ready,
        lambda_V_8 => lambda_V_5_reg_810,
        lambda_V_13 => trunc_ln84_reg_799,
        ret_11 => ret_8_reg_804,
        lambda_V_14_out => grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_lambda_V_14_out,
        lambda_V_14_out_ap_vld => grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_lambda_V_14_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv332_lc_2;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                    ap_return_preg <= ap_phi_mux_storemerge2_phi_fu_107_p4;
                end if; 
            end if;
        end if;
    end process;


    grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_ready = ap_const_logic_1)) then 
                    grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_ready = ap_const_logic_1)) then 
                    grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln1068_fu_211_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_ready = ap_const_logic_1)) then 
                    grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_ready = ap_const_logic_1)) then 
                    grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_ready = ap_const_logic_1)) then 
                    grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln1068_fu_211_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_ready = ap_const_logic_1)) then 
                    grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    g_V_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1064_fu_174_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                g_V_fu_90 <= ap_const_lv166_lc_2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                g_V_fu_90 <= g_V_1_fu_329_p3;
            end if; 
        end if;
    end process;

    storemerge2_reg_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1064_fu_174_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                storemerge2_reg_104 <= zext_ln1064_fu_162_p1;
            elsif (((icmp_ln1064_reg_663 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                storemerge2_reg_104 <= xor_i_i77_partset_fu_583_p3;
            end if; 
        end if;
    end process;

    tmp_V_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1064_fu_174_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                tmp_V_fu_94 <= ap_const_lv166_lc_1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                tmp_V_fu_94 <= ret_6_fu_423_p2;
            end if; 
        end if;
    end process;

    u_V_2_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1064_fu_174_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                u_V_2_fu_82 <= u_V_5_fu_158_p1;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                u_V_2_fu_82 <= u_V_fu_418_p2;
            end if; 
        end if;
    end process;

    v_V_1_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1064_fu_174_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                v_V_1_fu_86 <= ap_const_lv166_lc_3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                v_V_1_fu_86 <= v_V_fu_335_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                g_V_load_reg_754 <= g_V_fu_90;
                r_1_reg_764 <= r_1_fu_391_p3;
                select_ln1691_reg_759 <= select_ln1691_fu_384_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                icmp_ln1064_reg_663 <= icmp_ln1064_fu_174_p2;
                trunc_ln58_1_reg_657 <= trunc_ln58_1_fu_170_p1;
                trunc_ln58_reg_652 <= trunc_ln58_fu_166_p1;
                u_V_5_reg_640 <= u_V_5_fu_158_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                j_1_reg_742 <= j_1_fu_310_p3;
                tmp_19_reg_748 <= j_1_fu_310_p3(16 downto 16);
                tmp_reg_734 <= j_fu_290_p2(16 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                lambda_V_5_reg_810 <= lambda_V_5_fu_552_p3;
                ret_8_reg_804 <= ret_8_fu_539_p2;
                trunc_ln84_reg_799 <= trunc_ln84_fu_525_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1068_fu_211_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                lambda_V_reg_714 <= lambda_V_fu_234_p3;
                p_Val2_s_reg_709 <= P_read(328 downto 166);
                p_ph1_reg_724 <= p_ph1_fu_252_p3;
                trunc_ln1544_1_reg_719 <= trunc_ln1544_1_fu_243_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                ret_7_reg_769 <= ret_7_fu_449_p2;
                select_ln820_1_reg_789 <= select_ln820_1_fu_499_p3;
                select_ln820_2_reg_794 <= select_ln820_2_fu_508_p3;
                trunc_ln1544_3_reg_774 <= trunc_ln1544_3_fu_454_p1;
                xor_ln1544_2_reg_779 <= xor_ln1544_2_fu_459_p2;
                xor_ln1544_3_reg_784 <= xor_ln1544_3_fu_465_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                trunc_ln1068_reg_701 <= trunc_ln1068_fu_206_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                v_V_1_load_reg_729 <= v_V_1_fu_86;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln1064_fu_174_p2, ap_CS_fsm_state2, icmp_ln1068_fu_211_p2, grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_done, grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_done, ap_CS_fsm_state8, ap_CS_fsm_state4, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_block_state4_on_subcall_done, ap_block_state8_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln1064_fu_174_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((icmp_ln1064_fu_174_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln1068_fu_211_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_boolean_0 = ap_block_state4_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state8 => 
                if (((ap_const_boolean_0 = ap_block_state8_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and (grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    add_ln28_1_fu_280_p2 <= std_logic_vector(unsigned(grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_i_4_out) + unsigned(ap_const_lv16_1));
    add_ln28_fu_270_p2 <= std_logic_vector(unsigned(grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_i_out) + unsigned(ap_const_lv16_1));
    and_ln_fu_483_p3 <= (tmp_s_fu_473_p4 & ap_const_lv166_lc_2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_done)
    begin
        if ((grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_done)
    begin
        if ((grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state13_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state4_on_subcall_done)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(ap_block_state8_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state8_on_subcall_done)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state4_on_subcall_done_assign_proc : process(grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_done, grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_done)
    begin
                ap_block_state4_on_subcall_done <= ((grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_done = ap_const_logic_0) or (grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_done = ap_const_logic_0));
    end process;


    ap_block_state8_on_subcall_done_assign_proc : process(grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_done, grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_done)
    begin
                ap_block_state8_on_subcall_done <= ((grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_done = ap_const_logic_0) or (grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_storemerge2_phi_fu_107_p4_assign_proc : process(icmp_ln1064_reg_663, xor_i_i77_partset_fu_583_p3, storemerge2_reg_104, ap_CS_fsm_state13)
    begin
        if (((icmp_ln1064_reg_663 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
            ap_phi_mux_storemerge2_phi_fu_107_p4 <= xor_i_i77_partset_fu_583_p3;
        else 
            ap_phi_mux_storemerge2_phi_fu_107_p4 <= storemerge2_reg_104;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_phi_mux_storemerge2_phi_fu_107_p4, ap_CS_fsm_state13, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            ap_return <= ap_phi_mux_storemerge2_phi_fu_107_p4;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    ashr_ln1691_fu_378_p2 <= std_logic_vector(shift_right(signed(g_V_1_fu_329_p3),to_integer(unsigned('0' & zext_ln1691_1_fu_368_p1(31-1 downto 0)))));
    g_V_1_fu_329_p3 <= 
        tmp_V_fu_94 when (tmp_reg_734(0) = '1') else 
        g_V_fu_90;
    grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_start <= grp_point_double_1_Pipeline_VITIS_LOOP_25_11_fu_134_ap_start_reg;
    grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_start <= grp_point_double_1_Pipeline_VITIS_LOOP_25_1_fu_128_ap_start_reg;
    grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_start <= grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_ap_start_reg;
    grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_start <= grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_ap_start_reg;
    grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_start <= grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_ap_start_reg;
    grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_start <= grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_ap_start_reg;
    icmp_ln1064_fu_174_p2 <= "1" when (u_V_5_fu_158_p1 = ap_const_lv166_lc_2) else "0";
    icmp_ln1068_fu_211_p2 <= "1" when (u_V_2_fu_82 = ap_const_lv166_lc_1) else "0";
    j_1_fu_310_p3 <= 
        sub_ln69_fu_304_p2 when (tmp_fu_296_p3(0) = '1') else 
        j_fu_290_p2;
    j_fu_290_p2 <= std_logic_vector(unsigned(zext_ln28_fu_276_p1) - unsigned(zext_ln65_fu_286_p1));
    lambda_V_10_fu_520_p2 <= (ret_7_reg_769 xor ap_const_lv166_lc_1);
    lambda_V_5_fu_552_p3 <= 
        lambda_V_10_fu_520_p2 when (p_Result_14_fu_546_p2(0) = '1') else 
        ap_const_lv166_lc_2;
    lambda_V_9_fu_408_p3 <= 
        g_V_load_reg_754 when (tmp_reg_734(0) = '1') else 
        tmp_V_fu_94;
    lambda_V_fu_234_p3 <= 
        tmp_V_fu_94 when (p_Result_s_fu_227_p3(0) = '1') else 
        ap_const_lv166_lc_2;
    lhs_V_fu_567_p4 <= grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_p_out(331 downto 166);
    or_ln40_1_fu_491_p3 <= (tmp_s_fu_473_p4 & ret_7_fu_449_p2);
    p_Result_14_fu_546_p2 <= (xor_ln1544_fu_530_p2 xor trunc_ln1544_4_fu_535_p1);
    p_Result_s_fu_227_p3 <= P_read(166 downto 166);
    p_ph1_fu_252_p3 <= (select_ln820_fu_246_p3 & u_V_5_reg_640);
    r_1_fu_391_p3 <= 
        ashr_ln1691_fu_378_p2 when (tmp_19_reg_748(0) = '1') else 
        shl_ln1691_1_fu_353_p2;
    r_fu_372_p2 <= std_logic_vector(shift_right(signed(v_V_fu_335_p3),to_integer(unsigned('0' & zext_ln1691_1_fu_368_p1(31-1 downto 0)))));
    ret_6_fu_423_p2 <= (r_1_reg_764 xor lambda_V_9_fu_408_p3);
    ret_7_fu_449_p2 <= (u_V_5_reg_640 xor grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_lambda_V_12_out);
    ret_8_fu_539_p2 <= (lambda_V_10_fu_520_p2 xor grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_p_0_03_i5179_out);
    ret_fu_577_p2 <= (lhs_V_fu_567_p4 xor grp_point_double_1_Pipeline_VITIS_LOOP_45_14_fu_150_lambda_V_14_out);
    select_ln1691_fu_384_p3 <= 
        r_fu_372_p2 when (tmp_19_reg_748(0) = '1') else 
        shl_ln1691_fu_347_p2;
    select_ln820_1_fu_499_p3 <= 
        or_ln40_1_fu_491_p3 when (xor_ln1544_3_fu_465_p2(0) = '1') else 
        and_ln_fu_483_p3;
    select_ln820_2_fu_508_p3 <= 
        ret_7_fu_449_p2 when (xor_ln1544_3_fu_465_p2(0) = '1') else 
        ap_const_lv166_lc_2;
    select_ln820_fu_246_p3 <= 
        u_V_5_reg_640 when (trunc_ln58_1_reg_657(0) = '1') else 
        ap_const_lv166_lc_2;
        sext_ln1691_1_fu_364_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub_ln1691_fu_359_p2),32));

        sext_ln1691_fu_340_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(j_1_reg_742),32));

    shl_ln1691_1_fu_353_p2 <= std_logic_vector(shift_left(unsigned(g_V_1_fu_329_p3),to_integer(unsigned('0' & zext_ln1691_fu_343_p1(31-1 downto 0)))));
    shl_ln1691_fu_347_p2 <= std_logic_vector(shift_left(unsigned(v_V_fu_335_p3),to_integer(unsigned('0' & zext_ln1691_fu_343_p1(31-1 downto 0)))));
    sub_ln1691_fu_359_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(j_1_reg_742));
    sub_ln69_fu_304_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(j_fu_290_p2));
    tmp_fu_296_p3 <= j_fu_290_p2(16 downto 16);
    tmp_s_fu_473_p4 <= grp_point_double_1_Pipeline_VITIS_LOOP_45_12_fu_121_p_out(331 downto 166);
    trunc_ln1068_fu_206_p1 <= tmp_V_fu_94(165 - 1 downto 0);
    trunc_ln1544_1_fu_243_p1 <= P_read(163 - 1 downto 0);
    trunc_ln1544_2_fu_445_p1 <= grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_lambda_V_12_out(163 - 1 downto 0);
    trunc_ln1544_3_fu_454_p1 <= ret_7_fu_449_p2(165 - 1 downto 0);
    trunc_ln1544_4_fu_535_p1 <= grp_point_double_1_Pipeline_VITIS_LOOP_45_13_fu_140_p_0_03_i5179_out(1 - 1 downto 0);
    trunc_ln1544_fu_441_p1 <= grp_point_double_1_Pipeline_VITIS_LOOP_45_1_fu_113_lambda_V_12_out(1 - 1 downto 0);
    trunc_ln58_1_fu_170_p1 <= P_read(1 - 1 downto 0);
    trunc_ln58_fu_166_p1 <= P_read(165 - 1 downto 0);
    trunc_ln84_fu_525_p1 <= lambda_V_10_fu_520_p2(165 - 1 downto 0);
    u_V_5_fu_158_p1 <= P_read(166 - 1 downto 0);
    u_V_6_fu_413_p3 <= 
        v_V_1_load_reg_729 when (tmp_reg_734(0) = '1') else 
        u_V_2_fu_82;
    u_V_fu_418_p2 <= (u_V_6_fu_413_p3 xor select_ln1691_reg_759);
    v_V_fu_335_p3 <= 
        u_V_2_fu_82 when (tmp_reg_734(0) = '1') else 
        v_V_1_fu_86;
    xor_i_i77_partset_fu_583_p3 <= (ret_fu_577_p2 & ret_8_reg_804);
    xor_ln1544_2_fu_459_p2 <= (trunc_ln1544_2_fu_445_p1 xor trunc_ln1544_1_reg_719);
    xor_ln1544_3_fu_465_p2 <= (trunc_ln58_1_reg_657 xor trunc_ln1544_fu_441_p1);
    xor_ln1544_fu_530_p2 <= (xor_ln1544_3_reg_784 xor ap_const_lv1_1);
    zext_ln1064_fu_162_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(u_V_5_fu_158_p1),332));
    zext_ln1691_1_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1691_1_fu_364_p1),166));
    zext_ln1691_fu_343_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln1691_fu_340_p1),166));
    zext_ln28_fu_276_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln28_fu_270_p2),17));
    zext_ln65_fu_286_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln28_1_fu_280_p2),17));
end behav;
