// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Radix2wDPM_point_add_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read12,
        ap_return
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [331:0] p_read;
input  [165:0] p_read1;
input  [165:0] p_read12;
output  [331:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[331:0] ap_return;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [328:0] trunc_ln1068_fu_167_p1;
reg   [328:0] trunc_ln1068_reg_607;
wire   [0:0] and_ln99_fu_183_p2;
reg   [0:0] and_ln99_reg_612;
wire   [165:0] lhs_V_fu_189_p1;
reg   [165:0] lhs_V_reg_616;
wire   [165:0] lhs_V_10_fu_193_p4;
reg   [165:0] lhs_V_10_reg_621;
wire   [0:0] icmp_ln100_fu_209_p2;
reg   [0:0] icmp_ln100_reg_627;
wire   [0:0] icmp_ln1064_fu_215_p2;
reg   [0:0] icmp_ln1064_reg_631;
wire   [165:0] ret_17_fu_221_p2;
reg   [165:0] ret_17_reg_663;
wire   [164:0] trunc_ln1068_1_fu_259_p1;
reg   [164:0] trunc_ln1068_1_reg_677;
wire    ap_CS_fsm_state2;
wire   [165:0] ret_18_fu_280_p2;
reg   [165:0] ret_18_reg_685;
wire   [0:0] icmp_ln1068_2_fu_264_p2;
wire   [165:0] c_V_fu_291_p3;
reg   [165:0] c_V_reg_690;
reg   [165:0] v_V_3_load_reg_695;
wire    ap_CS_fsm_state3;
wire   [0:0] tmp_21_fu_336_p3;
reg   [0:0] tmp_21_reg_700;
wire    ap_CS_fsm_state5;
wire  signed [16:0] j_3_fu_350_p3;
reg  signed [16:0] j_3_reg_708;
reg   [0:0] tmp_22_reg_714;
reg   [165:0] g_V_load_reg_720;
wire    ap_CS_fsm_state6;
wire   [165:0] select_ln1691_fu_424_p3;
reg   [165:0] select_ln1691_reg_725;
wire   [165:0] r_3_fu_431_p3;
reg   [165:0] r_3_reg_730;
wire   [0:0] p_Result_18_fu_482_p1;
reg   [0:0] p_Result_18_reg_738;
wire    ap_CS_fsm_state9;
wire   [165:0] d_V_fu_486_p3;
reg   [165:0] d_V_reg_743;
wire   [165:0] d_V_3_fu_508_p2;
reg   [165:0] d_V_3_reg_748;
wire    ap_CS_fsm_state11;
wire   [164:0] trunc_ln1544_7_fu_519_p1;
reg   [164:0] trunc_ln1544_7_reg_754;
wire   [165:0] a_V_fu_524_p3;
reg   [165:0] a_V_reg_759;
wire   [331:0] grp_point_double_1_fu_162_ap_return;
wire    ap_CS_fsm_state15;
wire   [331:0] p_partset5_fu_553_p3;
wire    ap_CS_fsm_state16;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_start;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_done;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_idle;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_ready;
wire   [165:0] grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_c_V_7_out;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_c_V_7_out_ap_vld;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_start;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_done;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_idle;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_ready;
wire   [15:0] grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_i_out;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_i_out_ap_vld;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_start;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_done;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_idle;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_ready;
wire   [15:0] grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_i_18_out;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_i_18_out_ap_vld;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_start;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_done;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_idle;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_ready;
wire   [165:0] grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_d_V_4_out;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_d_V_4_out_ap_vld;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_start;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_done;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_idle;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_ready;
wire   [165:0] grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_a_V_4_out;
wire    grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_a_V_4_out_ap_vld;
wire    grp_point_double_1_fu_162_ap_start;
wire    grp_point_double_1_fu_162_ap_done;
wire    grp_point_double_1_fu_162_ap_idle;
wire    grp_point_double_1_fu_162_ap_ready;
reg   [331:0] ap_phi_mux_P_3_phi_fu_114_p10;
reg   [331:0] P_3_reg_110;
wire   [331:0] xor_i_partset_fu_545_p3;
wire    ap_CS_fsm_state13;
wire   [0:0] icmp_ln1064_1_fu_247_p2;
reg    grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_start_reg;
wire    ap_CS_fsm_state8;
reg    grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_start_reg;
wire    ap_CS_fsm_state4;
reg    grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_start_reg;
reg    grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_start_reg;
wire    ap_CS_fsm_state10;
reg    grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_point_double_1_fu_162_ap_start_reg;
wire    ap_CS_fsm_state14;
reg   [165:0] u_V_11_fu_76;
wire   [165:0] u_V_fu_458_p2;
wire    ap_CS_fsm_state7;
reg   [165:0] v_V_3_fu_80;
wire   [165:0] v_V_fu_375_p3;
reg   [165:0] g_V_fu_84;
wire   [165:0] g_V_3_fu_369_p3;
reg   [165:0] tmp_V_fu_88;
wire   [165:0] ret_19_fu_463_p2;
wire   [0:0] icmp_ln1068_fu_171_p2;
wire   [0:0] icmp_ln1068_1_fu_177_p2;
wire   [165:0] or_ln100_fu_203_p2;
wire   [0:0] tmp_fu_273_p3;
wire   [0:0] trunc_ln1544_fu_270_p1;
wire   [0:0] p_Result_s_fu_285_p2;
wire   [15:0] add_ln28_fu_310_p2;
wire   [15:0] add_ln28_3_fu_320_p2;
wire   [16:0] zext_ln28_fu_316_p1;
wire   [16:0] zext_ln65_fu_326_p1;
wire   [16:0] j_fu_330_p2;
wire   [16:0] sub_ln69_fu_344_p2;
wire  signed [31:0] sext_ln1691_fu_380_p1;
wire   [165:0] zext_ln1691_fu_383_p1;
wire   [16:0] sub_ln1691_fu_399_p2;
wire  signed [31:0] sext_ln1691_3_fu_404_p1;
wire   [165:0] zext_ln1691_3_fu_408_p1;
wire   [165:0] r_fu_412_p2;
wire   [165:0] shl_ln1691_fu_387_p2;
wire   [165:0] ashr_ln1691_fu_418_p2;
wire   [165:0] shl_ln1691_3_fu_393_p2;
wire   [165:0] u_V_15_fu_453_p3;
wire   [165:0] c_V_6_fu_448_p3;
wire   [165:0] xor_ln904_2_fu_502_p2;
wire   [165:0] xor_ln904_fu_498_p2;
wire   [165:0] ret_20_fu_514_p2;
wire   [165:0] xor_ln1544_fu_535_p2;
wire   [165:0] ret_fu_540_p2;
reg   [331:0] ap_return_preg;
reg   [15:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_block_state4_on_subcall_done;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_start_reg = 1'b0;
#0 grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_start_reg = 1'b0;
#0 grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_start_reg = 1'b0;
#0 grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_start_reg = 1'b0;
#0 grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_start_reg = 1'b0;
#0 grp_point_double_1_fu_162_ap_start_reg = 1'b0;
#0 ap_return_preg = 332'd0;
end

Radix2wDPM_point_add_2_Pipeline_VITIS_LOOP_45_1 grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_start),
    .ap_done(grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_done),
    .ap_idle(grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_idle),
    .ap_ready(grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_ready),
    .c_V(c_V_reg_690),
    .c_V_1(trunc_ln1068_1_reg_677),
    .ret_21(ret_18_reg_685),
    .c_V_7_out(grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_c_V_7_out),
    .c_V_7_out_ap_vld(grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_c_V_7_out_ap_vld)
);

Radix2wDPM_point_add_2_Pipeline_VITIS_LOOP_25_1 grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_start),
    .ap_done(grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_done),
    .ap_idle(grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_idle),
    .ap_ready(grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_ready),
    .u_V_14(u_V_11_fu_76),
    .i_out(grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_i_out),
    .i_out_ap_vld(grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_i_out_ap_vld)
);

Radix2wDPM_point_add_2_Pipeline_VITIS_LOOP_25_16 grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_start),
    .ap_done(grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_done),
    .ap_idle(grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_idle),
    .ap_ready(grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_ready),
    .v_V_6(v_V_3_fu_80),
    .i_18_out(grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_i_18_out),
    .i_18_out_ap_vld(grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_i_18_out_ap_vld)
);

Radix2wDPM_point_add_2_Pipeline_VITIS_LOOP_45_17 grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_start),
    .ap_done(grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_done),
    .ap_idle(grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_idle),
    .ap_ready(grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_ready),
    .d_V(d_V_reg_743),
    .c_V_7_reload(grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_c_V_7_out),
    .d_V_4_out(grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_d_V_4_out),
    .d_V_4_out_ap_vld(grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_d_V_4_out_ap_vld)
);

Radix2wDPM_point_add_2_Pipeline_VITIS_LOOP_45_18 grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_start),
    .ap_done(grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_done),
    .ap_idle(grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_idle),
    .ap_ready(grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_ready),
    .a_V(a_V_reg_759),
    .ret_23(trunc_ln1544_7_reg_754),
    .c_V_7_reload(grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_c_V_7_out),
    .a_V_4_out(grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_a_V_4_out),
    .a_V_4_out_ap_vld(grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_a_V_4_out_ap_vld)
);

Radix2wDPM_point_double_1 grp_point_double_1_fu_162(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_point_double_1_fu_162_ap_start),
    .ap_done(grp_point_double_1_fu_162_ap_done),
    .ap_idle(grp_point_double_1_fu_162_ap_idle),
    .ap_ready(grp_point_double_1_fu_162_ap_ready),
    .P_read(trunc_ln1068_reg_607),
    .ap_return(grp_point_double_1_fu_162_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 332'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            ap_return_preg <= ap_phi_mux_P_3_phi_fu_114_p10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_ready == 1'b1)) begin
            grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_ready == 1'b1)) begin
            grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_ready == 1'b1)) begin
            grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_ready == 1'b1)) begin
            grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1068_2_fu_264_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_start_reg <= 1'b1;
        end else if ((grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_ready == 1'b1)) begin
            grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_point_double_1_fu_162_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state14)) begin
            grp_point_double_1_fu_162_ap_start_reg <= 1'b1;
        end else if ((grp_point_double_1_fu_162_ap_ready == 1'b1)) begin
            grp_point_double_1_fu_162_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1064_fu_215_p2 == 1'd1) & (icmp_ln100_fu_209_p2 == 1'd0) & (1'd1 == and_ln99_fu_183_p2) & (icmp_ln1064_1_fu_247_p2 == 1'd0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        P_3_reg_110 <= 332'd0;
    end else if (((1'd0 == and_ln99_fu_183_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        P_3_reg_110 <= p_read;
    end else if (((grp_point_double_1_fu_162_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
        P_3_reg_110 <= grp_point_double_1_fu_162_ap_return;
    end else if (((icmp_ln1064_reg_631 == 1'd0) & (icmp_ln100_reg_627 == 1'd0) & (1'd1 == and_ln99_reg_612) & (1'b1 == ap_CS_fsm_state13))) begin
        P_3_reg_110 <= xor_i_partset_fu_545_p3;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        P_3_reg_110 <= p_partset5_fu_553_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1064_fu_215_p2 == 1'd0) & (icmp_ln100_fu_209_p2 == 1'd0) & (1'd1 == and_ln99_fu_183_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        g_V_fu_84 <= 166'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        g_V_fu_84 <= g_V_3_fu_369_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1064_fu_215_p2 == 1'd0) & (icmp_ln100_fu_209_p2 == 1'd0) & (1'd1 == and_ln99_fu_183_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_V_fu_88 <= 166'd1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_V_fu_88 <= ret_19_fu_463_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1064_fu_215_p2 == 1'd0) & (icmp_ln100_fu_209_p2 == 1'd0) & (1'd1 == and_ln99_fu_183_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        u_V_11_fu_76 <= ret_17_fu_221_p2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        u_V_11_fu_76 <= u_V_fu_458_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1064_fu_215_p2 == 1'd0) & (icmp_ln100_fu_209_p2 == 1'd0) & (1'd1 == and_ln99_fu_183_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        v_V_3_fu_80 <= 166'd11692013098647223345629478661730264157247460344009;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        v_V_3_fu_80 <= v_V_fu_375_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        a_V_reg_759 <= a_V_fu_524_p3;
        d_V_3_reg_748 <= d_V_3_fu_508_p2;
        trunc_ln1544_7_reg_754 <= trunc_ln1544_7_fu_519_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        and_ln99_reg_612 <= and_ln99_fu_183_p2;
        trunc_ln1068_reg_607 <= trunc_ln1068_fu_167_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1068_2_fu_264_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        c_V_reg_690 <= c_V_fu_291_p3;
        ret_18_reg_685 <= ret_18_fu_280_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        d_V_reg_743 <= d_V_fu_486_p3;
        p_Result_18_reg_738 <= p_Result_18_fu_482_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        g_V_load_reg_720 <= g_V_fu_84;
        r_3_reg_730 <= r_3_fu_431_p3;
        select_ln1691_reg_725 <= select_ln1691_fu_424_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln99_fu_183_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln100_reg_627 <= icmp_ln100_fu_209_p2;
        lhs_V_10_reg_621 <= {{p_read[331:166]}};
        lhs_V_reg_616 <= lhs_V_fu_189_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln100_fu_209_p2 == 1'd0) & (1'd1 == and_ln99_fu_183_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln1064_reg_631 <= icmp_ln1064_fu_215_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        j_3_reg_708 <= j_3_fu_350_p3;
        tmp_21_reg_700 <= j_fu_330_p2[32'd16];
        tmp_22_reg_714 <= j_3_fu_350_p3[32'd16];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1064_fu_215_p2 == 1'd0) & (icmp_ln100_fu_209_p2 == 1'd0) & (1'd1 == and_ln99_fu_183_p2) & (1'b1 == ap_CS_fsm_state1))) begin
        ret_17_reg_663 <= ret_17_fu_221_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln1068_1_reg_677 <= trunc_ln1068_1_fu_259_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        v_V_3_load_reg_695 <= v_V_3_fu_80;
    end
end

always @ (*) begin
    if ((grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

always @ (*) begin
    if ((grp_point_double_1_fu_162_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1064_reg_631 == 1'd0) & (icmp_ln100_reg_627 == 1'd0) & (1'd1 == and_ln99_reg_612) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_phi_mux_P_3_phi_fu_114_p10 = xor_i_partset_fu_545_p3;
    end else begin
        ap_phi_mux_P_3_phi_fu_114_p10 = P_3_reg_110;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_return = ap_phi_mux_P_3_phi_fu_114_p10;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln1064_fu_215_p2 == 1'd1) & (icmp_ln100_fu_209_p2 == 1'd0) & (1'd1 == and_ln99_fu_183_p2) & (icmp_ln1064_1_fu_247_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if (((icmp_ln1064_fu_215_p2 == 1'd0) & (icmp_ln100_fu_209_p2 == 1'd0) & (1'd1 == and_ln99_fu_183_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((icmp_ln100_fu_209_p2 == 1'd1) & (1'd1 == and_ln99_fu_183_p2) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & ((1'd0 == and_ln99_fu_183_p2) | ((icmp_ln1064_fu_215_p2 == 1'd1) & (icmp_ln100_fu_209_p2 == 1'd0) & (icmp_ln1064_1_fu_247_p2 == 1'd0))))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln1068_2_fu_264_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            if (((grp_point_double_1_fu_162_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_V_fu_524_p3 = ((p_Result_18_reg_738[0:0] == 1'b1) ? ret_20_fu_514_p2 : 166'd0);

assign add_ln28_3_fu_320_p2 = (grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_i_18_out + 16'd1);

assign add_ln28_fu_310_p2 = (grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_i_out + 16'd1);

assign and_ln99_fu_183_p2 = (icmp_ln1068_fu_171_p2 & icmp_ln1068_1_fu_177_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_done == 1'b0) | (grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_done == 1'b0));
end

assign ashr_ln1691_fu_418_p2 = $signed(g_V_3_fu_369_p3) >>> zext_ln1691_3_fu_408_p1;

assign c_V_6_fu_448_p3 = ((tmp_21_reg_700[0:0] == 1'b1) ? g_V_load_reg_720 : tmp_V_fu_88);

assign c_V_fu_291_p3 = ((p_Result_s_fu_285_p2[0:0] == 1'b1) ? tmp_V_fu_88 : 166'd0);

assign d_V_3_fu_508_p2 = (xor_ln904_fu_498_p2 ^ xor_ln904_2_fu_502_p2);

assign d_V_fu_486_p3 = ((p_Result_18_fu_482_p1[0:0] == 1'b1) ? grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_c_V_7_out : 166'd0);

assign g_V_3_fu_369_p3 = ((tmp_21_reg_700[0:0] == 1'b1) ? tmp_V_fu_88 : g_V_fu_84);

assign grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_start = grp_point_add_2_Pipeline_VITIS_LOOP_25_16_fu_141_ap_start_reg;

assign grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_start = grp_point_add_2_Pipeline_VITIS_LOOP_25_1_fu_135_ap_start_reg;

assign grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_start = grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_ap_start_reg;

assign grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_start = grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_ap_start_reg;

assign grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_start = grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_ap_start_reg;

assign grp_point_double_1_fu_162_ap_start = grp_point_double_1_fu_162_ap_start_reg;

assign icmp_ln100_fu_209_p2 = ((or_ln100_fu_203_p2 == 166'd0) ? 1'b1 : 1'b0);

assign icmp_ln1064_1_fu_247_p2 = ((lhs_V_10_fu_193_p4 == p_read12) ? 1'b1 : 1'b0);

assign icmp_ln1064_fu_215_p2 = ((lhs_V_fu_189_p1 == p_read1) ? 1'b1 : 1'b0);

assign icmp_ln1068_1_fu_177_p2 = ((p_read12 != 166'd0) ? 1'b1 : 1'b0);

assign icmp_ln1068_2_fu_264_p2 = ((u_V_11_fu_76 == 166'd1) ? 1'b1 : 1'b0);

assign icmp_ln1068_fu_171_p2 = ((p_read1 != 166'd0) ? 1'b1 : 1'b0);

assign j_3_fu_350_p3 = ((tmp_21_fu_336_p3[0:0] == 1'b1) ? sub_ln69_fu_344_p2 : j_fu_330_p2);

assign j_fu_330_p2 = (zext_ln28_fu_316_p1 - zext_ln65_fu_326_p1);

assign lhs_V_10_fu_193_p4 = {{p_read[331:166]}};

assign lhs_V_fu_189_p1 = p_read[165:0];

assign or_ln100_fu_203_p2 = (lhs_V_fu_189_p1 | lhs_V_10_fu_193_p4);

assign p_Result_18_fu_482_p1 = grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_c_V_7_out[0:0];

assign p_Result_s_fu_285_p2 = (trunc_ln1544_fu_270_p1 ^ tmp_fu_273_p3);

assign p_partset5_fu_553_p3 = {{p_read12}, {p_read1}};

assign r_3_fu_431_p3 = ((tmp_22_reg_714[0:0] == 1'b1) ? ashr_ln1691_fu_418_p2 : shl_ln1691_3_fu_393_p2);

assign r_fu_412_p2 = $signed(v_V_fu_375_p3) >>> zext_ln1691_3_fu_408_p1;

assign ret_17_fu_221_p2 = (p_read1 ^ lhs_V_fu_189_p1);

assign ret_18_fu_280_p2 = (p_read12 ^ lhs_V_10_reg_621);

assign ret_19_fu_463_p2 = (r_3_reg_730 ^ c_V_6_fu_448_p3);

assign ret_20_fu_514_p2 = (lhs_V_reg_616 ^ d_V_3_fu_508_p2);

assign ret_fu_540_p2 = (xor_ln1544_fu_535_p2 ^ d_V_3_reg_748);

assign select_ln1691_fu_424_p3 = ((tmp_22_reg_714[0:0] == 1'b1) ? r_fu_412_p2 : shl_ln1691_fu_387_p2);

assign sext_ln1691_3_fu_404_p1 = $signed(sub_ln1691_fu_399_p2);

assign sext_ln1691_fu_380_p1 = j_3_reg_708;

assign shl_ln1691_3_fu_393_p2 = g_V_3_fu_369_p3 << zext_ln1691_fu_383_p1;

assign shl_ln1691_fu_387_p2 = v_V_fu_375_p3 << zext_ln1691_fu_383_p1;

assign sub_ln1691_fu_399_p2 = ($signed(17'd0) - $signed(j_3_reg_708));

assign sub_ln69_fu_344_p2 = (17'd0 - j_fu_330_p2);

assign tmp_21_fu_336_p3 = j_fu_330_p2[32'd16];

assign tmp_fu_273_p3 = p_read[32'd166];

assign trunc_ln1068_1_fu_259_p1 = tmp_V_fu_88[164:0];

assign trunc_ln1068_fu_167_p1 = p_read[328:0];

assign trunc_ln1544_7_fu_519_p1 = ret_20_fu_514_p2[164:0];

assign trunc_ln1544_fu_270_p1 = p_read12[0:0];

assign u_V_15_fu_453_p3 = ((tmp_21_reg_700[0:0] == 1'b1) ? v_V_3_load_reg_695 : u_V_11_fu_76);

assign u_V_fu_458_p2 = (u_V_15_fu_453_p3 ^ select_ln1691_reg_725);

assign v_V_fu_375_p3 = ((tmp_21_reg_700[0:0] == 1'b1) ? u_V_11_fu_76 : v_V_3_fu_80);

assign xor_i_partset_fu_545_p3 = {{ret_fu_540_p2}, {d_V_3_reg_748}};

assign xor_ln1544_fu_535_p2 = (lhs_V_10_reg_621 ^ grp_point_add_2_Pipeline_VITIS_LOOP_45_18_fu_154_a_V_4_out);

assign xor_ln904_2_fu_502_p2 = (grp_point_add_2_Pipeline_VITIS_LOOP_45_17_fu_147_d_V_4_out ^ 166'd1);

assign xor_ln904_fu_498_p2 = (ret_17_reg_663 ^ grp_point_add_2_Pipeline_VITIS_LOOP_45_1_fu_127_c_V_7_out);

assign zext_ln1691_3_fu_408_p1 = $unsigned(sext_ln1691_3_fu_404_p1);

assign zext_ln1691_fu_383_p1 = $unsigned(sext_ln1691_fu_380_p1);

assign zext_ln28_fu_316_p1 = add_ln28_fu_310_p2;

assign zext_ln65_fu_326_p1 = add_ln28_3_fu_320_p2;

endmodule //Radix2wDPM_point_add_2
